name: DashLord scans

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      url:
        description: "Single url with repositories to scan e.g. url\\;repo1,repo2 or empty to scan all urls"
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - 'dashlord.yaml'
      - 'dashlord.yml'
      - 'urls.txt'

jobs:
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      urls: ${{ steps.init.outputs.urls }}
      sites: ${{ steps.init.outputs.sites }}
    steps:
      - uses: actions/checkout@v2
      - id: init
        uses: "SocialGouv/dashlord-actions/init@main"

  scans:
    runs-on: ubuntu-latest
    name: Scan
    needs: init
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        sites: ${{ fromJson(needs.init.outputs.sites) }}
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir scans

      - run: |
          echo url: ${{ matrix.sites.url }}
          echo repositories: ${{ join(matrix.sites.repositories) }}

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Déclaration a11y
        continue-on-error: true
        uses: "socialgouv/dashlord-actions/declaration-a11y@v1"
        if: ${{ matrix.sites.tools['declaration-a11y'] }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/declaration-a11y.json
          
      - name: eco-index
        continue-on-error: true
        uses: "socialgouv/dashlord-actions/ecoindex@v1"
        if: ${{ matrix.sites.tools.ecoindex }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/ecoindex.json

      - name: Detect 404s
        continue-on-error: true
        timeout-minutes: 10
        uses: "socialgouv/detect-404-action@master"
        if: ${{ matrix.sites.tools['404'] }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/404.json

      - name: Wappalyzer scan
        uses: "socialgouv/wappalyzer-action@master"
        if: ${{ matrix.sites.tools.wappalyzer }}
        continue-on-error: true
        timeout-minutes: 10
        with:
          url: "${{ matrix.sites.url }}"
          output: scans/wappalyzer.json

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        if: ${{ matrix.sites.tools.zap }}
        continue-on-error: true
        timeout-minutes: 10
        with:
          token: "" # disable issue creation
          docker_name: "owasp/zap2docker-stable"
          target: "${{ matrix.sites.url }}"
          cmd_options: "-a"

      - name: Lighthouse scan
        continue-on-error: true
        timeout-minutes: 10
        uses: treosh/lighthouse-ci-action@v9
        if: ${{ matrix.sites.tools.lighthouse }}
        with:
          urls: "${{ matrix.sites.url }}"
          uploadArtifacts: false
          temporaryPublicStorage: false
          configPath: "./lighthouserc.json"

      - name: Mozilla HTTP Observatory
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/httpobs-action@master
        if: ${{ matrix.sites.tools.http }}
        with:
          url: "${{ matrix.sites.url }}"
          output: "scans/http.json"

      - name: Third-party scripts scan
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/thirdparties-action@master
        if: ${{ matrix.sites.tools.thirdparties }}
        with:
          url: "${{ matrix.sites.url }}"
          output: "scans/thirdparties.json"          
          
      - name: Déclaration RGPD
        continue-on-error: true
        uses: SocialGouv/dashlord-actions/declaration-rgpd@v1
        if: ${{ matrix.sites.tools['declaration-rgpd'] }}
        with:
          thirdparties: ${{ steps.thirdparties.outputs.json }}
          url: ${{ matrix.sites.url }}
          output: scans/declaration-rgpd.json

      # testssl.sh action needs an hostname to save its output so we build it here
      - name: Extract hostname
        id: hostname
        run: |
          HOSTNAME=$(echo "${{ matrix.sites.url }}" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
          echo "::set-output name=value::$HOSTNAME"

      - name: testssl.sh scan
        continue-on-error: true
        timeout-minutes: 10
        uses: "mbogh/test-ssl-action@v1.1"
        if: ${{ matrix.sites.tools.testssl }}
        with:
          host: ${{ steps.hostname.outputs.value }}
          output: scans
          grade: "F"
          options: "--fast"

      - name: nmap vulnerabilities scan
        continue-on-error: true
        timeout-minutes: 10
        uses: "MTES-MCT/nmap-action@main"
        if: ${{ matrix.sites.tools.nmap }}
        with:
          host: ${{ steps.hostname.outputs.value }}
          outputDir: 'scans'
          outputFile: 'nmapvuln.json'
          withVulnerabilities: true
          raw: false
          
      - name: Nuclei scan
        continue-on-error: true
        timeout-minutes: 10
        uses: "SocialGouv/dashlord-nuclei-action@master"
        if: ${{ matrix.sites.tools.nuclei }}
        with:
          url: ${{ matrix.sites.url }}
          output: "scans/nuclei.log"

      - name: Updown.io checks
        continue-on-error: true
        timeout-minutes: 10
        uses: "MTES-MCT/updownio-action@main"
        if: ${{ matrix.sites.tools.updownio }}
        with:
          apiKey: ${{ secrets.UPDOWNIO_API_KEY }}
          url: ${{ matrix.sites.url }}
          output: scans/updownio.json

      - name: Dependabot vulnerabilities alerts
        continue-on-error: true
        timeout-minutes: 10
        uses: "MTES-MCT/dependabotalerts-action@main"
        if: ${{ matrix.sites.tools.dependabot && matrix.sites.repositories }}
        with:
          token: ${{ secrets.DEPENDABOTALERTS_TOKEN }}
          repositories: ${{ join(matrix.sites.repositories) }}
          maxAlerts: 20
          states: OPEN
          output: scans/dependabotalerts.json

      - name: Code quality alerts
        continue-on-error: true
        timeout-minutes: 10
        uses: "MTES-MCT/codescanalerts-action@main"
        if: ${{ matrix.sites.tools.codescan && matrix.sites.repositories }}
        with:
          token: ${{ secrets.CODESCANALERTS_TOKEN }}
          repositories: ${{ join(matrix.sites.repositories) }}
          state: open
          output: scans/codescanalerts.json

      - name: Betagouv API scan
        if: ${{ matrix.sites.tools.betagouv }}
        continue-on-error: true
        timeout-minutes: 10
        id: betagouv
        uses: betagouv/dashlord-startup-action@main
        with:
          id: "${{ matrix.sites.betaId }}"
          output: "scans/betagouv.json"

      - name: Stats page
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@main"
        if: ${{ matrix.sites.tools.stats }}
        with:
          url: ${{ steps.betagouv.outputs.stats_url }}
          output: scans/stats.json
          minExpectedRegex: ^stat
          exactExpectedRegex: ^stats$
          
      - name: Budget page
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@main"
        if: ${{ matrix.sites.tools.budget_page }}
        with:
          url: ${{ steps.betagouv.outputs.budget_url }}
          output: scans/budget_page.json
          exactExpectedRegex: ^budget$
          
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        if: ${{ matrix.sites.tools.screenshot }}
        continue-on-error: true
        timeout-minutes: 10
        with:
          source: "${{ matrix.sites.url }}"
          destination: screenshot.jpeg
          width: 1280

      - uses: SocialGouv/dashlord-actions/save@main
        with:
          url: ${{ matrix.sites.url }}

      - uses: EndBug/add-and-commit@v7
        with:
          add: '["results"]'
          default_author: github_actions
          message: "update: ${{ matrix.sites.url }}"
